services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest@sha256:5286edb35782454ab8a102c5eff6b54bff745853191b46aeead95f225aa6dfb6
    ports:
      - "8889:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
