services:
  searxng:
    container_name: searxng
    image: searxng/searxng@sha256:11a9b34cdc0b1ec2b991470a2762ecb5a1a531898289fb51dcd015260450729e
    ports:
      - "8889:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
