import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { parse as parseToml, TomlError } from "smol-toml";
import { DEFAULT_CONFIG_DIR_NAME, LEGACY_CONFIG_DIR_NAME } from "./app.js";
import type { Config } from "./types.js";

/**
 * Default config file path.
 */
const DEFAULT_CONFIG_PATH = join(
  homedir(),
  ".config",
  DEFAULT_CONFIG_DIR_NAME,
  "config.toml"
);
const LEGACY_CONFIG_PATH = join(
  homedir(),
  ".config",
  LEGACY_CONFIG_DIR_NAME,
  "config.toml"
);

/**
 * Resolve the effective config file path: explicit `--config`, then the default
 * path, then the legacy brand path (whichever exists first).
 */
export function resolveConfigPath(configPath?: string): string {
  if (configPath) {
    return configPath;
  }

  if (existsSync(DEFAULT_CONFIG_PATH)) {
    return DEFAULT_CONFIG_PATH;
  }

  if (existsSync(LEGACY_CONFIG_PATH)) {
    return LEGACY_CONFIG_PATH;
  }

  // Neither config exists — use default path for error messaging so guidance
  // points users at the new brand, not the legacy name.
  return DEFAULT_CONFIG_PATH;
}

/**
 * TOML parse errors embed the offending source excerpt (smol-toml carries it
 * in `TomlError.codeblock`), which may hold literal credentials. Keep the
 * location/reason prefix and drop the source excerpt so secrets never surface
 * in error output.
 */
function sanitizeTomlError(message: string): string {
  const firstNewline = message.indexOf("\n");
  return firstNewline === -1 ? message : message.slice(0, firstNewline);
}

/**
 * Load and parse configuration from a TOML file.
 */
export function loadConfig(configPath?: string): Config {
  const path = resolveConfigPath(configPath);
  
  let content: string;
  try {
    content = readFileSync(path, "utf-8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      const defaultPath = `~/.config/${DEFAULT_CONFIG_DIR_NAME}/config.toml`;
      const guidance = path === DEFAULT_CONFIG_PATH
        ? `Create one at ${defaultPath} or specify with --config`
        : `Verify the --config path or create the file at ${path}`;

      throw new Error(`Config file not found: ${path}\n${guidance}`);
    }
    throw error;
  }

  let parsed: unknown;
  try {
    parsed = parseToml(content);
  } catch (error) {
    // Keep the structured position (never the source excerpt) so the operator
    // gets a location without any credential material.
    const location =
      error instanceof TomlError ? ` (line ${error.line}, column ${error.column})` : "";
    throw new Error(
      `Failed to parse config file ${path}${location}: ${sanitizeTomlError((error as Error).message)}`
    );
  }

  // `[agent.llm] base_url` (snake_case) is the documented TOML spelling; the
  // runtime reads camelCase `baseUrl`, so normalize. Either spelling works —
  // `baseUrl` wins if both are present. Only normalize when `agent.llm` is a
  // plain object: malformed shapes (string, array, …) are left for
  // `config doctor` to report as a config error.
  const llm = (parsed as { agent?: { llm?: unknown } }).agent?.llm;
  if (
    llm !== undefined &&
    llm !== null &&
    typeof llm === "object" &&
    !Array.isArray(llm)
  ) {
    const llmCfg = llm as { base_url?: string; baseUrl?: string };
    if (llmCfg.base_url !== undefined && llmCfg.baseUrl === undefined) {
      llmCfg.baseUrl = llmCfg.base_url;
    }
  }

  return parsed as unknown as Config;
}

/**
 * Get providers for a capability from config.
 */
export function getProvidersForCapability(
  config: Config,
  capability: string
): string[] {
  const capConfig = config.capabilities[capability];
  if (!capConfig) {
    throw new Error(`Capability '${capability}' not found in config`);
  }
  return capConfig.providers;
}

/**
 * Get provider configuration.
 */
export function getProviderConfig(
  config: Config,
  provider: string
): Config["providers"][string] {
  const providerConfig = config.providers[provider];
  if (!providerConfig) {
    throw new Error(`Provider '${provider}' not found in config`);
  }
  return providerConfig;
}

export { DEFAULT_CONFIG_PATH, LEGACY_CONFIG_PATH };

/**
 * Starter config written by `coldsearch config init`.
 *
 * Deliberately minimal: empty provider pools (nothing assumed about the
 * operator's accounts) with comments that point at the full example. It is a
 * valid, doctor-clean baseline the operator fills in — never a config that
 * resolves secrets on its own.
 */
export const STARTER_CONFIG = `# Starter configuration generated by \`coldsearch config init\`.
# Full reference: config.example.toml and docs/CONFIGURATION.md.
#
# Add providers to each capability pool, e.g. providers = ["searxng", "tavily"],
# then add a [providers.<name>] block with a key pool per provider:
#
#   [providers.tavily]
#   [providers.tavily.keyPool]
#   keys = ["doppler:TAVILY_API_KEY"]   # or env:TAVILY_API_KEY
#
# Key references store secret NAMES only — never literal values in this file.

[capabilities.search]
providers = []
strategy = "random"

[capabilities.extract]
providers = []
strategy = "random"

[capabilities.crawl]
providers = []
strategy = "random"

# Key pools are declared per provider; add one block per provider here.
# Key references store secret NAMES only — never literal values in this file.
[providers]

# Agent LLM endpoint (optional): OpenAI-compatible chat completions.
# CLI flags --llm / --model / --llm-base-url override these values.
# [agent.llm]
# provider = "openai"
# model = "gpt-4o"
# base_url = "https://api.openai.com/v1"
`;
